# Generated by Django 6.0.6 on 2026-07-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorcount',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
